const https = require('https');
const fs = require('fs');
const path = require('path');

/**
 * NOTE: To render SVG files in React Native, you need to install:
 * npm install react-native-svg
 * npm install -D react-native-svg-transformer
 * 
 * Also, make sure to configure your metro.config.js to handle SVG files.
 */

const BASE_URL = 'https://raw.githubusercontent.com/rsapkf/20/main/3x3/cfop/';

const CONFIG = [
  {
    type: 'f2l',
    count: 41,
    dest: 'assets/images/cubes/resolution/3x3/full_fridrich/f2l/',
    sourcePath: (i) => `f2l/svg/${i}.svg` // Predicted path, but browser found f2l is missing
  },
  {
    type: 'oll',
    count: 57,
    dest: 'assets/images/cubes/resolution/3x3/full_fridrich/oll/',
    sourcePath: (i) => `oll/svg/${i}.svg`
  },
  {
    type: 'pll',
    count: 21,
    dest: 'assets/images/cubes/resolution/3x3/full_fridrich/pll/',
    mapping: ['Aa', 'Ab', 'E', 'F', 'Ga', 'Gb', 'Gc', 'Gd', 'H', 'Ja', 'Jb', 'Na', 'Nb', 'Ra', 'Rb', 'T', 'Ua', 'Ub', 'V', 'Y', 'Z'],
    sourcePath: (i, mapping) => `pll/svg/${mapping[i-1]}.svg`
  }
];

const INDEX_FILE = path.join(__dirname, '../src/data/imageIndex.ts');

async function downloadFile(url, dest) {
  return new Promise((resolve, reject) => {
    const file = fs.createWriteStream(dest);
    https.get(url, (response) => {
      if (response.statusCode !== 200) {
        reject(new Error(`Failed to download ${url}: ${response.statusCode}`));
        return;
      }
      response.pipe(file);
      file.on('finish', () => {
        file.close(resolve);
      });
    }).on('error', (err) => {
      fs.unlink(dest, () => reject(err));
    });
  });
}

async function main() {
  console.log('🚀 Starting asset download...');
  
  const indexEntries = {
    f2l: {},
    oll: {},
    pll: {}
  };

  for (const group of CONFIG) {
    const fullDestPath = path.join(__dirname, '..', group.dest);
    if (!fs.existsSync(fullDestPath)) {
      fs.mkdirSync(fullDestPath, { recursive: true });
    }

    console.log(`\n📦 Downloading ${group.type.toUpperCase()} assets...`);
    
    for (let i = 1; i <= group.count; i++) {
      const sourceName = group.sourcePath ? group.sourcePath(i, group.mapping) : `${group.type}${i}.svg`;
      const url = `${BASE_URL}${sourceName}`;
      const fileName = `${group.type}${i}.svg`;
      const dest = path.join(fullDestPath, fileName);
      
      try {
        await downloadFile(url, dest);
        process.stdout.write('.');
        
        const relativePath = `../../${group.dest}${fileName}`;
        indexEntries[group.type][`${group.type}${i}`] = relativePath;
      } catch (error) {
        if (group.type === 'f2l') {
           // Silence F2L errors as they are known to be missing from this repo
        } else {
           console.error(`\n❌ Error downloading ${fileName} from ${url}: ${error.message}`);
        }
      }
    }
  }

  if (Object.keys(indexEntries.f2l).length === 0) {
    console.warn('\n⚠️  Note: F2L assets were not found in the repository. You might need an alternative source.');
  }

  console.log('\n\n📄 Generating imageIndex.ts...');
  
  let indexContent = `/**
 * Automatically generated by scripts/fetch_github_assets.js
 * 
 * NOTE: For these SVGs to work in React Native, ensure you have installed:
 * - react-native-svg
 * - react-native-svg-transformer
 */\n\n`;

  indexContent += 'export const imageIndex: { [key: string]: { [key: string]: any } } = {\n';
  
  for (const [type, files] of Object.entries(indexEntries)) {
    indexContent += `  ${type}: {\n`;
    for (const [name, path] of Object.entries(files)) {
      indexContent += `    ${name}: require('${path}'),\n`;
    }
    indexContent += '  },\n';
  }
  
  indexContent += '};\n';

  fs.writeFileSync(INDEX_FILE, indexContent);
  console.log(`✅ Done! Assets downloaded and ${INDEX_FILE} generated.`);
}

main().catch(console.error);
