const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = path.join(__dirname, '..');
const ASSETS_ROOT = path.join(PROJECT_ROOT, 'assets/images/cubes');
const OUTPUT_FILE = path.join(PROJECT_ROOT, 'src/data/imageIndex.ts');

/**
 * Mapeo inverso de nombres de archivo a llaves de objeto (ej. R_prime -> R')
 */
const FILE_TO_KEY_MAP = {
    'L_prime': "L'", 'R_prime': "R'", 'U_prime': "U'", 'D_prime': "D'", 'F_prime': "F'", 'B_prime': "B'",
    'l_prime': "l'", 'r_prime': "r'", 'u_prime': "u'", 'd_prime': "d'", 'f_prime': "f'", 'b_prime': "b'",
    'M_prime': "M'", 'E_prime': "E'", 'S_prime': "S'"
};

function formatKey(fileName) {
    const baseName = fileName.split('.')[0];
    return FILE_TO_KEY_MAP[baseName] || baseName;
}

function scanDirectory(dir, relPath = '') {
    const absolutePath = path.join(ASSETS_ROOT, relPath);
    if (!fs.existsSync(absolutePath)) return null;

    const items = fs.readdirSync(absolutePath);
    const result = {};

    items.forEach(item => {
        const itemPath = path.join(absolutePath, item);
        const stats = fs.statSync(itemPath);

        if (stats.isDirectory()) {
            const subDir = scanDirectory(dir, path.join(relPath, item));
            if (subDir && Object.keys(subDir).length > 0) {
                result[item] = subDir;
            }
        } else if (stats.size > 0 && (item.endsWith('.svg') || item.endsWith('.webp') || item.endsWith('.png'))) {
            const key = formatKey(item);
            // Generamos la ruta relativa para el require
            // Desde src/data/ hacia assets/images/cubes/
            const requirePath = `../../assets/images/cubes/${relPath.replace(/\\/g, '/')}/${item}`;
            result[key] = `REQUIRE_START${requirePath}REQUIRE_END`;
        } else if (stats.size === 0) {
            console.warn(`[!] Omitiendo archivo vacío: ${path.join(relPath, item)}`);
        }
    });

    return result;
}

console.log('--- Generando imageIndex.ts ---');

const assetsTree = scanDirectory(ASSETS_ROOT);

if (!assetsTree) {
    console.error('No se pudo encontrar la carpeta de assets.');
    process.exit(1);
}

// Convertimos el objeto a string y reemplazamos los placeholders por requires reales
let jsonString = JSON.stringify(assetsTree, null, 2);
const finalContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is generated by scripts/generate_index.js
 */

export const CubeAssets: any = ${jsonString.replace(/"REQUIRE_START([^"]+)REQUIRE_END"/g, "require('$1')")};
`;

fs.writeFileSync(OUTPUT_FILE, finalContent);

console.log('--- Índice generado correctamente en src/data/imageIndex.ts ---');

// Reporte de conteo
const countAssets = (obj) => {
    let count = 0;
    for (const key in obj) {
        if (typeof obj[key] === 'string' && obj[key].includes('require')) count++;
        else if (typeof obj[key] === 'object') count += countAssets(obj[key]);
    }
    return count;
};
// Nota: en el string final ya no son strings, pero el objeto assetsTree antes del stringify sí.
// Re-escaneamos de forma simple para el reporte
console.log(`Total de activos válidos encontrados: ${finalContent.split('require(').length - 1}`);
