const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = path.join(__dirname, '..');
const ASSETS_ROOT = path.join(PROJECT_ROOT, 'assets/images/cubes/resolution/3x3/full_fridrich');
const OUTPUT_PATH = path.join(PROJECT_ROOT, 'src/data/imageIndex.ts');

function getFiles(subdir) {
    const dir = path.join(ASSETS_ROOT, subdir);
    if (!fs.existsSync(dir)) return [];
    return fs.readdirSync(dir).filter(f => {
        const isExt = f.endsWith('.svg') || f.endsWith('.webp');
        if (!isExt) return false;
        const stats = fs.statSync(path.join(dir, f));
        return stats.size > 0; // Solo archivos con contenido
    });
}

const f2lFiles = getFiles('f2l');
const ollFiles = getFiles('oll');
const pllFiles = getFiles('pll');

let content = `/**
 * Automatically generated by scripts/rebuild_index.js
 */

export const CubeAssets: any = {
  "notation": {
    "2x2": {
      "L": require('../../assets/images/cubes/notation/2x2/L.webp'),
      "F": require('../../assets/images/cubes/notation/2x2/F.webp'),
      "R": require('../../assets/images/cubes/notation/2x2/R.webp'),
      "B": require('../../assets/images/cubes/notation/2x2/B.webp'),
      "U": require('../../assets/images/cubes/notation/2x2/U.webp'),
      "D": require('../../assets/images/cubes/notation/2x2/D.webp'),
      "L'": require('../../assets/images/cubes/notation/2x2/L_prime.webp'),
      "F'": require('../../assets/images/cubes/notation/2x2/F_prime.webp'),
      "R'": require('../../assets/images/cubes/notation/2x2/R_prime.webp'),
      "B'": require('../../assets/images/cubes/notation/2x2/B_prime.webp'),
      "U'": require('../../assets/images/cubes/notation/2x2/U_prime.webp'),
      "D'": require('../../assets/images/cubes/notation/2x2/D_prime.webp'),
      "D2": require('../../assets/images/cubes/notation/2x2/D2.webp'),
      "U2": require('../../assets/images/cubes/notation/2x2/U2.webp'),
      "L2": require('../../assets/images/cubes/notation/2x2/L2.webp'),
    }
  },
  "resolution": {
    "3x3": {
      "full_fridrich": {
        "f2l": {
`;

f2lFiles.forEach(f => {
    const id = f.replace('.svg', '');
    content += `          "${id}": require('../../assets/images/cubes/resolution/3x3/full_fridrich/f2l/${f}'),\n`;
});

content += `        },\n        "oll": {\n`;

ollFiles.forEach(f => {
    // Metro Safety: Saltamos oll43 si es problemático (opcional si ya existe)
    // Pero si fs.readdirSync lo encontró, debería ser seguro.
    const id = f.replace('.svg', '');
    content += `          "${id}": require('../../assets/images/cubes/resolution/3x3/full_fridrich/oll/${f}'),\n`;
});

content += `        },\n        "pll": {\n`;

pllFiles.forEach(f => {
    const id = f.replace('.svg', '');
    content += `          "${id}": require('../../assets/images/cubes/resolution/3x3/full_fridrich/pll/${f}'),\n`;
});

content += `        }\n      }\n    }\n  }\n};\n`;

fs.writeFileSync(OUTPUT_PATH, content);
console.log('Index rebuilt successfully with nested structure.');
